version: 2
orbs:
  aws-s3: circleci/aws-s3@1.0.0
jobs:
  build:
    working_directory: ~/temp
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-package
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: zip-package
          command: 'zip -r sample-node-dependency-lib.zip .'
      - store_artifacts:
          path: sample-node-dependency-lib.zip
      - - run:
          name: copy-artifact-to-s3
          command: 'aws s3 sync sample-node-dependency-lib.zip s://sample-node-dependency-lib'